version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"

    volumes:
      - odoo-version:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
  db:
    ports:
      - "5442:5432"
  
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-version-db:/var/lib/postgresql/data/pgdata
volumes:
  odoo-version:
  odoo-version-db:


